eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

---

spring:
  profiles: dev

api:
  title: Planet Service
  description: Cloud Planet Service 
  version: 1.0.0-BETA
  contactname: Jose Oliveros
  contacturl: https://trycore.co/
  contactemail: jomiol91@gmail.com
  basepackage: com.cloud.planet.rest.controller
